services:
  - type: web
    name: telegram-bot-genio-financeiro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
